name: CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"
      - "server/**"
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - "server/**"
      - ".github/workflows/**"

permissions:
  contents: read

concurrency:
  group: terraform-production
  cancel-in-progress: false

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  provision:
    name: Provision
    needs: test
    uses: ./.github/workflows/terraform.yml
    permissions:
      contents: read
      id-token: write
