name: CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"
      - "server/**"
      - "frontend/**"
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - "server/**"
      - "frontend/**"
      - ".github/**"

permissions:
  contents: read

concurrency:
  group: terraform-production
  cancel-in-progress: false

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  provision:
    name: Provision
    needs: test
    uses: ./.github/workflows/terraform.yml
    permissions:
      contents: read
      id-token: write

  build-push:
    name: Build/Push
    needs: provision
    if: github.event_name == 'push'
    uses: ./.github/workflows/build-push.yml
    permissions:
      contents: read
      id-token: write
    with:
      frontend_repository_url: ${{ needs.provision.outputs.frontend_repository_url }}
      server_repository_url: ${{ needs.provision.outputs.server_repository_url }}
      cognito_user_pool_id: ${{ needs.provision.outputs.cognito_user_pool_id }}
      cognito_app_client_id: ${{ needs.provision.outputs.cognito_app_client_id }}
      aws_region: ${{ needs.provision.outputs.aws_region }}
